### ISSUE TITLE
[audit functionality] Return the correct occurrence of the secret text in a line

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#110] opened 2018-12-28 23:02 UTC
If you have e.g.

```python
self.thepassword = "thepassword" 
```
and run the soon-to-be-merged keyword detector, then run the audit functionality, it will highlight the first occurrence, and instead of the second. This is a bug.

This is because in `audit.py` we find the index of the secret https://github.com/Yelp/detect-secrets/blob/1415b4b86913d77be805ec2593b7d7339661e03d/detect_secrets/core/audit.py#L561
and we don't return the index of the secret in the [`secret_generator`](https://github.com/Yelp/detect-secrets/blob/1415b4b86913d77be805ec2593b7d7339661e03d/detect_secrets/plugins/base.py#L50) method of plugins.

This somewhat related to the issue of handling multiple secrets on the same line https://github.com/Yelp/detect-secrets/blob/1415b4b86913d77be805ec2593b7d7339661e03d/detect_secrets/plugins/base.py#L76

**Comment by KevinHock** [comment] 2019-01-03 01:33
On a related note, w/r/t the Keyword detector, the biggest source of not specific-to-yelp false-positives are variables like `FORGOT_PASSWORD: 'forgot_password'` where LHS == RHS, maybe I shouldn't flag these, as I've only seen false-positives, but not catching `password = 'password'` would irk me.

**Comment by lorenzodb1** [comment] 2024-05-09 17:11
Closing as duplicate of #493.

**Closed by lorenzodb1** 2024-05-09 17:11 UTC
Labels: duplicate, bug
