### ISSUE TITLE
unrecognized arguments: --word-list

### ISSUE THREAD

**Issue by BhaskiBuzz** [Yelp/detect-secrets#514] opened 2022-02-07 07:49 UTC
Hi Team,

I am trying to use --word-list argument like below. but it is saying the argument is unkown

```
detect-secrets scan --word-list a/b/c/WORD_LIST_FILE --no-verify --all-files
usage: detect-secrets [-h] [-v] [--version] [-C <path>] [-c NUM_CORES]
                      {scan,audit} ...
detect-secrets: error: unrecognized arguments: --word-list
```

detect-secrets --version: 1.1.0

**Comment by lorenzodb1** [comment] 2022-04-06 22:12
Closing as I cannot reproduce the issue on version 1.2.0

**Comment by mark-pictor-csec** [comment] 2022-04-08 21:28
also seen with v1.2.0 installed from pip.
python 3.8, pip 22.0.4, osx

**Comment by lorenzodb1** [comment] 2022-04-08 22:51
Hi @mark-pictor-csec! Thank you for reporting this. I was able to reproduce the issue and, therefore, I will reopen this issue and further investigate this issue.

**Comment by mark-pictor-csec** [comment] 2022-04-11 15:05
I did not. That seems to fix it, as `--word-list` now appears in the help output - haven't actually tested yet.

**Comment by jpdakran** [comment] 2022-04-11 16:23
Some documentation on the `word-list` feature: https://github.com/Yelp/detect-secrets#wordlist

**Closed** 2022-04-11 16:27 UTC

**Comment by mark-pictor-csec** [comment] 2022-04-11 17:16
I read over that and somehow missed the required dependency; I also looked at the code but didn't see what the problem was. I'm a little surprised I didn't see something in the code, but then again python isn't a language I use much.

Would it be possible to check unrecognized args, and if `--word-list` is one, tell the user to install `pyahocorasick`?

**Comment by lorenzodb1** [comment] 2022-04-11 18:04
@mark-pictor-csec thank you for your suggestion. We will look into that.

**Comment by BhaskiBuzz** [comment] 2022-04-13 06:44
Hi @lorenzodb1 @jpdakran I am able to use --word-list after installing the pyahocorasick package.
Thank you
