### ISSUE TITLE
ERROR: No plugins to scan with

### ISSUE THREAD

**Issue by s1mrankaur** [Yelp/detect-secrets#454] opened 2021-04-16 22:47 UTC
This is what my .secrets.baseline looks like:
```

{
  "version": "1.1.0",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "Base64HighEntropyString",
      "limit": 4.5
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "HexHighEntropyString",
      "limit": 3.0
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    },
    {
      "path": "detect_secrets.filters.heuristic.is_indirect_reference"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_lock_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_not_alphanumeric_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_swagger_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_templated_secret"
    },
    {
      "path": "detect_secrets.filters.regex.should_exclude_file",
      "pattern": [
        "*.test.js",
        "*-lock.json"
      ]
    }
  ],
  "results": {},
  "generated_at": "2021-04-16T22:42:24Z"
}

```

It excludes files with patterns:
```

      "path": "detect_secrets.filters.regex.should_exclude_file",
      "pattern": [
        "*.test.js",
        "*-lock.json"
      ]
    }
```
Now, when I run 

`detect-secrets scan`, I get the following result:
```

$ detect-secrets scan
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
{
  "version": "1.1.0",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "Base64HighEntropyString",
      "limit": 4.5
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "HexHighEntropyString",
      "limit": 3.0
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    },
    {
      "path": "detect_secrets.filters.heuristic.is_indirect_reference"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_lock_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_not_alphanumeric_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_swagger_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_templated_secret"
    }
  ],
  "results": {},
  "generated_at": "2021-04-16T22:44:22Z"
}

```

**Comment by domanchi** [comment] 2021-04-17 00:46
Possible duplicate of #452 .

**Closed by domanchi** 2021-04-17 00:46 UTC
