### ISSUE TITLE
Calling detect-secrets from another Python script

### ISSUE THREAD

**Issue by Tioborto** [Yelp/detect-secrets#350] opened 2020-10-09 11:58 UTC
Hello,

I would need your insights on this subject. 
I am currently working on a project that will allow us to scan our entire Github organization (20,000 repos). Is it possible, at this time of the day, to call the scan of a repo, after cloning it, from another python script?
If so, can you please guide me please? 

Best regards

**Comment by domanchi** [comment] 2020-10-09 15:44
Hi @Tioborto,

If you're asking whether it's possible to invoke a scan of a repository from another python script, have you checked out whether [detect-secrets-server](https://github.com/Yelp/detect-secrets-server) meets your needs?

**Comment by nymous** [comment] 2020-10-12 12:15
Hi,
What we are looking for is a way to programmatically use `detect-secrets`. The idea is not having to run `subprocess.run('detect-secrets scan --all-files')` and then parse the console output in a dict, but instead do something like this:
<details>
<summary>Expand code block</summary>

```py
from detect-secrets import scan

results = scan('path/to/local/folder', all_files=True)
print(results)  # `results` would be a dict/TypedDict/class with what is printed in the console after a scan
"""
{
  "custom_plugin_paths": [],
  "exclude": {
    "files": ".venv|.mypy_cache",
    "lines": null
  },
  "generated_at": "2020-10-12T11:51:46Z",
  "plugins_used": [
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "ArtifactoryDetector"
    },
    {
      "base64_limit": 4.5,
      "name": "Base64HighEntropyString"
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "hex_limit": 3,
      "name": "HexHighEntropyString"
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "keyword_exclude": null,
      "name": "KeywordDetector"
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "results": {
    "poetry.lock": [
      {
        "hashed_secret": "0a2c2daece8f4cf5f09c2f9ba92212e852295579",
        "is_verified": false,
        "line_number": 146,
        "type": "Hex High Entropy String"
      }
    ]
  },
  "version": "0.14.3",
  "word_list": {
    "file": null,
    "hash": null
  }
}
```
</details>

For now we've been diving in `detect-secrets` source to try to copy and adapt the code that is run by the CLI. I'm looking at `detect-secrets-server` to see if it's easier to hook into it that way, but maybe that's still not the right approach...

**Comment by 3lpsy** [comment] 2020-11-04 21:11
@Tioborto I can confirm that it's possible to integrate detect-secrets into your own scripts. Each plugin as an 'adhoc_scan' method that can be called. You can see how this is done by just searching for 'adhoc_scan' in main.py. The annoying thing is that you have to generate a list of the plugins before you can loop over them an call this method. You can find out how to do this by searching for 'initialize' in 'main.py'. However, to get that to work programatically without cli args, you'll need to need to yoink the 'consolidate_args' logic from 'core/usage.py'. You want the generated 'active_plugins' variable to grab to base plugins (this is what you'll loop over and call adhoc_scan). You'll need to work around the fact that 'args' doesn't exist and also consider that some plugins (i believe) need default args like 'base64_limit', 'hex_limit', and 'keyword_exclude'. It shouldn't take more than an hour to figure out but it would be nice if there was just a 'get_base_plugins_im_lazy_and_dont_care_about_custom_stuff' method. Something like that may already exist but I was in a hurry.

**Comment by KevinHock** [comment] 2020-11-04 22:11
We should fix this but I just wanna say, that's one of the best dive-in's I've ever seen on this project @3lpsy!

**Comment by domanchi** [comment] 2020-11-04 23:24
FWIW, when I first wrote this tool ~3 years ago, I never imagined it would gain this much community traction. It's been simply astounding watching the growth of this project (and thanks to all the contributors along the way!)

Since then, my coding style has improved drastically. This tool has reached some level of maturity, and I'm in the middle of a large refactor to make this:

1. Easier to be extensible (both through plugins, and building your own scripts leveraging `detect-secrets` as a dependency)
2. Easier to grok, with clearer coding patterns for the system's internals

Watch this space for exciting updates in the coming month!

**Comment by domanchi** [comment] 2020-11-17 01:43
This experience is drastically improved in the new `pre-v1-launch` branch. If you're curious, be sure to check it out: https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/CONTRIBUTING.md

An example of how you would call detect-secrets in v1 is described in the docs: https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/plugins.md#configuring-plugins.

I'm going to close this issue as this will be fixed in the next version (currently in progress).

**Closed by domanchi** 2020-11-17 01:43 UTC
