### ISSUE TITLE
ValueError: unichr() arg not in range(0x10000) 

### ISSUE THREAD

**Issue by HenryHoggard** [Yelp/detect-secrets#305] opened 2020-05-29 10:04 UTC
Just trying out this tool, after installing with pip and executing the below command in a git repo, I get the following error.

`detect-secrets scan`

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/detect-secrets", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/main.py", line 47, in main
    baseline_dict = _perform_scan(args, plugins)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/main.py", line 146, in _perform_scan
    scan_all_files=args.all_files,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/core/baseline.py", line 58, in initialize
    output.scan_file(file)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/core/secrets_collection.py", line 208, in scan_file
    self._extract_secrets_from_file(f, filename_key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/core/secrets_collection.py", line 308, in _extract_secrets_from_file
    results.update(plugin.analyze(f, filename))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/high_entropy_strings.py", line 71, in analyze
    output = analyze_function(file, filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/high_entropy_strings.py", line 213, in _analyze_yaml_file
    data = parser.json()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/common/yaml_file_parser.py", line 55, in json
    return self.loader.get_single_data()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    node = self.get_single_node()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/common/yaml_file_parser.py", line 60, in _compose_node_shim
    node = yaml.composer.Composer.compose_node(self.loader, parent, index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/common/yaml_file_parser.py", line 60, in _compose_node_shim
    node = yaml.composer.Composer.compose_node(self.loader, parent, index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/common/yaml_file_parser.py", line 60, in _compose_node_shim
    node = yaml.composer.Composer.compose_node(self.loader, parent, index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/common/yaml_file_parser.py", line 60, in _compose_node_shim
    node = yaml.composer.Composer.compose_node(self.loader, parent, index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/common/yaml_file_parser.py", line 60, in _compose_node_shim
    node = yaml.composer.Composer.compose_node(self.loader, parent, index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/detect_secrets/plugins/common/yaml_file_parser.py", line 60, in _compose_node_shim
    node = yaml.composer.Composer.compose_node(self.loader, parent, index)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py", line 1155, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py", line 1223, in scan_flow_scalar_non_spaces
    chunks.append(unichr(code))
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
```

**Comment by domanchi** [comment] 2020-05-30 14:15
Wow. From the stack trace, looks like the issue is with your YAML file. From a quick Google search, it also looks like the [issue can be addressed by moving to Python3](https://stackoverflow.com/a/7105944).

My hypothesis is that it's nothing to do with `detect-secrets` itself. To verify this, you can try:

```
# Attempt to find the YAML file containing unicode (you might need to modify the grep query)
$ find . -name '*.yaml' | xargs grep 'u"'

# Try to open that file manually.
$ python -i
>>> import yaml
>>> yaml.load(<path-to-file>)
```

**Comment by HenryHoggard** [comment] 2020-06-01 10:44
Hi @domanchi, which yaml file are you referring to?

**Comment by HenryHoggard** [comment] 2020-06-02 07:38
Is it worth having a fallback to simple text based loading of the file if the yaml parsing doesn't work?

**Comment by domanchi** [comment] 2020-11-18 15:16
@HenryHoggard, if you would like, you can certainly contribute a PR to the v1 branch (https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/detect_secrets/transformers/yaml.py#L29). However, given that we've deprecated Python2.7 usage (and soon to be deprecating Python3.6), I'm going to close this as "Won't Fix".

Secrets in un-parseable files fall in the realm of philosophical questions. In order to improve scan speeds and reduce false positives, I'm opting **not** to scan things that will not be used as a secret source in regular usage. This being said, I will still accept a PR that modifies this (as it shouldn't change intended behavior much).

**Closed by domanchi** 2020-11-18 15:16 UTC
Labels: question
