### ISSUE TITLE
Secrets are not found in Jupyter Notebooks 

### ISSUE THREAD

**Issue by mosc9575** [Yelp/detect-secrets#781] opened 2024-01-02 15:51 UTC
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**

If  I open an new Jupyter Notebook (in JupyterLab 4.0.9) and write in the first cell

```python
def my_very_secret_function(my_password = "bar"):
    pass
```

see secret is not found while using detect secrets as a pre-commit hook.

This is because the cell has the following form in the saved file.

```
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa11ab85-ce4e-4803-92c9-0f48e2ce4c52",
   "metadata": {},
   "outputs": [],
   "source": [
    "def my_very_secret_function(my_password = \"bar\"):\n",
    "    pass"
   ]
  }
```

As you can see there is a backslash `\` before the quotation mark `"`. I think because of this no regular expressions matches the secret.

* **What is the expected behavior?**
I expect that `detect_secrets` finds secrets in pure python and jupyter notebooks.
* **Technical information**

Detect secrets version    : 1.4.0
Python version      :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
IPython version     :  8.14.0
Tornado version     :  6.3.3
Operating system    :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.35
JupyterLab version    : 4.0.9

**Comment by lorenzodb1** [comment] 2024-05-16 18:09
Closing as duplicate of https://github.com/Yelp/detect-secrets/issues/780.

**Closed by lorenzodb1** 2024-05-16 18:09 UTC
Labels: duplicate
